name = "RiemannRecognitionGeometry"
defaultTargets = ["RiemannRecognitionGeometry"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.16.0"

[[lean_lib]]
name = "RiemannRecognitionGeometry"
